disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "BookFinds"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
   logo = "logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Rodkirsten Bayran"
#   email = "youremail@example.com"
   image = "cat.jpg"
#   imageQuality = 100
#   headline = "I'm only human"
#   bio = "A little bit about you"
   links = [
     { facebook = "https://www.facebook.com/kirsten.bayran" },
     { instagram = "https://www.instagram.com/rodkirsten_" },
     { telegram = "https://t.me/Kersten" },
 ]
