[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Book Recommendation"
pageRef = "books"
weight = 4

[[main]]
  name = "Categories"
  parent = "Book Recommendation"
  pageRef = "categories"
  weight = 2

[[main]]
  name = "Tags"
  parent = "Book Recommendation"
  pageRef = "tags"
  weight = 1   

[[main]]
name = "About"
pageRef = "about"
weight = 2

[[main]]
name = "Contact"
pageRef = "contact"
weight = 3

[[main]]
identifier = "github"
pre = "github"
url = "https://github.com/rodkirstenbayran"
weight = 300

#[[footer]]
#name = "Tags"
#pageRef = "tags"
#weight = 1

#[[footer]]
#name = "Categories"
#pageRef = "categories"
#weight = 2
